name: Build container
on:
  push:
    branches: main
jobs:
  build:
    runs-on: docker
    steps:
      - uses: https://github.com/docker/setup-qemu-action@v3
      - uses: https://github.com/docker/setup-buildx-action@v3
      - uses: https://github.com/docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - uses: https://github.com/docker/build-push-action@v6
        with:
          push: false
          tags: davidized/hugo-build:latest
